### ISSUE TITLE
How to write unit test case for treeview when it's in virtual Mode ?

### ISSUE THREAD

**Issue by MM-RYO** [lidorsystems/integralui-treeview#1]
Hi,
I have tried to disable virtual mode in unit test case but it won't work.
how to query tree-item element from debug element of tree component. currently I only can see the root element being rendered.
please give some advise. thanks a lot.

**Comment by Lidor-Systems** [comment]
Does this happen with 20.1?
Try out the updated version that is part of the [IntegralUI Web](https://github.com/lidorsystems/integralui-web).

**Note**   This repository is not updated to 20.1. In near future this repository will include TreeView built on Web Components standard, and you can use the TreeView not just in Angular but also in React, Vue etc.

**Comment by MM-RYO** [comment]
> Does this happen with 20.1?
> Try out the updated version that is part of the [IntegralUI Web](https://github.com/lidorsystems/integralui-web).
> 
> **Note** This repository is not updated to 20.1. In near future this repository will include TreeView built on Web Components standard, and you can use the TreeView not just in Angular but also in React, Vue etc.

I am using 19.*

**Comment by Lidor-Systems** [comment]
Try to switch to 20.1.

**Comment by MM-RYO** [comment]
> Try to switch to 20.1.

It's hard to do it now.

**Comment by Lidor-Systems** [comment]
> I have tried to disable virtual mode in unit test case but it won't work.

Why it doesn't work? Can you give us more information?

> how to query tree-item element from debug element of tree component

Please give us more information on how you debug the TreeView?
A sample that demonstrates this is helpful.
